Document: openvpn-otp
Title: Debian openvpn-otp Manual
Author: <insert document author here>
Abstract: This manual describes what openvpn-otp is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/openvpn-otp/openvpn-otp.sgml.gz

Format: postscript
Files: /usr/share/doc/openvpn-otp/openvpn-otp.ps.gz

Format: text
Files: /usr/share/doc/openvpn-otp/openvpn-otp.text.gz

Format: HTML
Index: /usr/share/doc/openvpn-otp/html/index.html
Files: /usr/share/doc/openvpn-otp/html/*.html
